FROM node:10.15-stretch

WORKDIR /app
COPY ida-chatbot/package.json package.json
COPY ida-chatbot/package-lock.json package-lock.json
RUN npm ci

COPY ida-chatbot/angular.json angular.json
COPY ida-chatbot/tsconfig.json tsconfig.json
COPY ida-chatbot/tslint.json tslint.json

EXPOSE 4200
CMD npm run start-container
