FROM ubuntu:18.04

RUN apt-get update && apt-get install \
  -y --no-install-recommends python3 python3-pip python3-setuptools python3-virtualenv

ENV VIRTUAL_ENV=~/venv_intent_classification
RUN python3 -m virtualenv --python=/usr/bin/python3 $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR /app
COPY intent-classification/requirements.txt intent-classification/requirements.txt
RUN pip3 install -r intent-classification/requirements.txt

WORKDIR /app/intent-classification
EXPOSE 5001
CMD python3 app.py
